# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_year',
            field=models.CharField(max_length=4),
        ),
    ]
