# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshop_app', '0002_auto_20170223_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/imgs/', verbose_name='Image'),
        ),
    ]
